version: "3.3"
services:
  server:
    build: .
    image: zobees/citadel
    volumes:
      - ./tmp:/citadel
    ports:
      - "7777:7777"
      - "7777:7777/udp"
      - "27015:27015"
      - "27015:27015/udp"